# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js enviroment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 14.x   
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          
      - name: Install dependencies
        run: yarn
      
      - name: Run build
        run: yarn build

      - name: Run tests
        run: yarn test
        
      - name: Copy build to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "~/mauri-backend"
      
      - name: Run production scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/mauri-backend
            yarn
            yarn migration
            yarn seed
            pm2 restart api-liconnection
